### ISSUE TITLE
使用TIDB作为trino数据库，报错'CREATE TABLE ... SELECT' is not implemented yet

### ISSUE THREAD

**Issue by TwowT969** [tidb-incubator/TiBigData#220]
你好，我的项目中使用TIDB数据库与trino，但在trino执行过程中，发现trino执行的sql中包含TIDB明确不支持的`CREATE TABLE tblName AS SELECT stmt `语法 ，请问有对应的解决办法吗？

**Comment by xuanyu66** [comment]
Yes, we don't support it yet. https://github.com/tidb-incubator/TiBigData/blob/master/trino/src/main/java/io/tidb/bigdata/trino/tidb/TiDBMetadata.java should implement these [two interface](https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java#L505-L526) in order to support 'CREATE TABLE ... SELECT'
